### ISSUE TITLE
https://docs.mobilitydb.com/ ERR_CONNECTION_TIMED_OUT

### ISSUE THREAD

**Issue by AlinaYablokova** [ULB-CoDE-WIT/MobilityDB#10]
Hello,

Why https://docs.mobilitydb.com/ does not response during last 3-5 days? Where could I get the documentation?

BR,
Alina.

**Comment by estebanzimanyi** [comment]
Dear Alina
Our university has suffered a major cyber attack. For the next days the situation is uncertain. Here is the current version of the documentation in pdf format.
[mobilitydb-manual.pdf](https://github.com/ULB-CoDE-WIT/MobilityDB/files/4292322/mobilitydb-manual.pdf)
[mobilitydb-workshop.pdf](https://github.com/ULB-CoDE-WIT/MobilityDB/files/4292324/mobilitydb-workshop.pdf)
