### ISSUE TITLE
What is the TB-tree mentioned in the document?

### ISSUE THREAD

**Issue by lyp-bobi** [ULB-CoDE-WIT/MobilityDB#13]
"GiST and SP-GiST indexes can be created for table columns of temporal types. The GiST index implements an R-tree for temporal alphanumeric types and a TB-tree for temporal point types."

I'm not quite sure about what does this TB-Tree refers to.  Is that the trajectory-bundle tree?

**Comment by estebanzimanyi** [comment]
Indeed, we meant Trajectory-Bundle tree, as in the corresponding paper
https://www.researchgate.net/publication/2395927_Novel_Approaches_to_the_Indexing_of_Moving_Object_Trajectories
However, on reflection, this is not fully exact. For both GiST and SP-GiST indexes, MobilityDB works with a single temporal or spatio-temporal box (the tbox and stbox data types) encompassing the full extent of the temporal type or temporal point.
The reason for this is that there is currently no infrastructure available in PostgreSQL to develop TB-Trees and thus this task has been left as a possible future development for MobilityDB. 
Many thanks for point this, we will correct this immediately.
