### ISSUE TITLE
Mobility DB with Docker Installation Issue

### ISSUE THREAD

**Issue by sherazahsan** [ULB-CoDE-WIT/MobilityDB#14]
Hi

I was try to install and configure Mobility DB. I have done following steps successfully 
$ docker pull codewit/mobilitydb
$  docker volume create mobilitydb_data
$  docker run --name "mobilitydb" -d -p 25432:5432 -v mobilitydb_data:/var/lib/postgresql codewit/mobilitydb

But was unable to verify if my mobility db is install. I have tried to connect mobilitydb database through postgres but no luck. When i try the command "create extension mobilitydb" in postgres it does not work. There occurs a following message:

![image](https://user-images.githubusercontent.com/45170605/81393293-8fcd9600-9139-11ea-869e-2f7ffa7e6a90.png)

Also when i try to run following command "docker exec -t -i mobilitydb psql -h localhost -p 5432 -d mobilitydb -U docker" it does not work and following message displays 
![image](https://user-images.githubusercontent.com/45170605/81393544-fbaffe80-9139-11ea-94ed-e2e93a533b8c.png)

**Comment by sherazahsan** [comment]
Actually there was some installation issue. For what i understood you need to first install Docker and then install MobilityDB. Its working now on my local machine

**Comment by sabman** [comment]
@sherazahsan Can you please close this issue then
