### ISSUE TITLE
Error on " Create extension mobilitydb cascade"

### ISSUE THREAD

**Issue by sherazahsan** [ULB-CoDE-WIT/MobilityDB#15]
Hi
I have installed Postgres 10 and Docker. I also successfully installed MobilityDB and got got access to the mobilitydb. 
My issue is when i try to create extension for the mobilitydb in the database., i come across the error given in below screenshot. Can anyone pl guide

![image](https://user-images.githubusercontent.com/45170605/81871933-38448580-9592-11ea-9c07-e0e6d67835de.png)

**Comment by alesuiss** [comment]
Hi,

Thanks for the report; there seems to be an issue with the upstream Docker image that we use. I'll see if I can work around.

In the meantime, a temporary fix is to force loading PostGIS before loading or running MobilityDB:

```
SELECT ST_Point(0, 0) ;
CREATE EXTENSION MobilityDB ;
```

**Comment by alesuiss** [comment]
Fixed in the latest Docker builds

**Comment by sherazahsan** [comment]
Thank you so much ... It done now

![image](https://user-images.githubusercontent.com/45170605/81981159-57eab500-9649-11ea-9668-b83122e51239.png)
