### ISSUE TITLE
undefined symbol: LWGEOM_setpoint_linestring

### ISSUE THREAD

**Issue by wendellwt** [ULB-CoDE-WIT/MobilityDB#2]
I'm trying to use the plugin but am having an "undefined symbol" problem.

I have PostgreSQL, PostGIS, and MobileDB all compiled from sources and installed (I don't have root access on the machine).  All of the compiles and installs seemed to go ok.
I'm following the examples in section 3.1, and the CREATE works fine:

```
mobile=# CREATE TABLE Department(DeptNo integer, DeptName varchar(25), NoEmps tint);
CREATE TABLE
```

However, the INSERT does not work:

```
mobile=# INSERT INTO Temperature VALUES
(1001, tfloat '{18.5@2012-01-01 08:00:00, 20.0@2012-01-01 08:10:00}'),
(2001, tfloat '{19.0@2012-01-01 08:00:00, 22.5@2012-01-01 08:10:00}');
ERROR:  could not load library "/home/data/local/lib/postgresql/libMobilityDB.so": /home/data/local/lib/postgresql/libMobilityDB.so: undefined symbol: LWGEOM_setpoint_linestring
```

The library seems to be in the right place:

```
[wturner@rserver ciws]$ ls -l /home/data/local/lib/postgresql/libMobilityDB.so
-rwxr-xr-x. 1 wturner wturner 1193288 Nov 26 11:00 /home/data/local/lib/postgresql/libMobilityDB.so
```

And it seems to have the right stuff:

```
[wturner@rserver ~]$ strings /home/data/local/lib/postgresql/libMobilityDB.so | grep setpoint_linestring
LWGEOM_setpoint_linestring
LWGEOM_setpoint_linestring
```

Also, the LD_LIBRARY_PATH is set to that directory.

Do you have any suggestions about what could be wrong?
Thank you,
Wendell

**Comment by alesuiss** [comment]
Hello,

It seems that PostGIS is not loaded; MobilityDB requires PostGIS to be loaded before any query. You should add this line to your postgresql.conf as documented in the README:

`shared_preload_libraries = 'postgis-2.5'`

Or, you can just issue a dummy PostGIS query like "SELECT ST_MakePoint(0,0)" to force the loading of PostGIS, and subsequent MobilityDB queries should work.

Cheers,
Arthur

**Comment by wendellwt** [comment]
That worked, thank you.  I had edited the wrong postgresql.conf file.  It works fine now.
