### ISSUE TITLE
problem with autovacuum and insert

### ISSUE THREAD

**Issue by wendellwt** [ULB-CoDE-WIT/MobilityDB#4]
Sirs,

First, thank you for creating this extension.  It works great, but I've run into an issue with inserts.

I use R, and within a loop it issues a dbWriteTable to create a temporary table of the data, then it uses SQL to insert that table into the MobilityDB table via:

`INSERT INTO  tz_2019_09_02 SELECT acid, fid, 
  tgeompointseq(array_agg(tgeompointinst(
    ST_SetSRID(ST_MakePoint(lng,lat),4326), times)
   ORDER BY times))
  FROM  tz_2019_09_02_inputs  GROUP BY acid, fid;`

The insert seems to succeed, but after the loop runs for a few hundred inserts, PostgreSQL crashes with:
`could not connect ... on dbname "mobile": FATAL:  the database system is in recovery mode`
and the pgsql logfile shows:
`Failed process was running: autovacuum: ANALYZE public.tz_2019_09_02`
It seems that I can get around the problem by first issuing:
`ALTER TABLE tz_2019_09_02 SET (autovacuum_enabled = false, toast.autovacuum_enabled = false);`
After issuing this ALTER statement the INSERT loop works fine with no errors.

Is this an issue with my underlying data? Or have I mis-configured PostGIS or MobilityDB?

Thank you,
Wendell

**Comment by estebanzimanyi** [comment]
Dear Wendell
Many thanks for your interest in MobilityDB. Could you please tell us whether you are using the last version (beta) of MobilityDB? Indeed, we have corrected several bugs we found out in the alpha version. 
Additionally, you can run analyze on your table to see whether the problem is still there. Please let us know so we can look at it.
Regards
Esteban

**Comment by wendellwt** [comment]
Esteban,
I downloaded today's git repo (Feb 4) and tried it.  It produces:
```
mobile=# INSERT INTO  tz_2019_09_02 SELECT acid, fid, tgeompointseq(array_agg(tgeompointinst(  ST_SetSRID(ST_MakePoint(lng,lat), 4326), times)   ORDER BY times))  FROM  tz_2019_09_02_inputs  GROUP BY acid, fid;
ERROR:  could not find function "temporal_make_temporalseq" in file "/home/data/local/lib/postgresql/libMobilityDB.so"
```
Wendell

**Comment by wendellwt** [comment]
Esteban,
Sorry, but I'm still having trouble.  I installed the new version (from today's git repo) and created a new database.

I moved the "INSERT INTO" from within the loop to outside; the loop creates about 525,000 records in the xxx_input table, then the "INSERT INTO" sql statement runs and inserts about 4,700 records (each with one tgeompointseq) into the main table.

Here is what is strange:
* the program generates 525,000 position records and inserts them into the xxx_input table
* the program executes `"ALTER TABLE tz_yyyy_mm_dd SET (autovacuum_enabled = false, toast.autovacuum_enabled = false);"`
* the program executes `"INSERT INTO tz_yyyy_mm_dd SELECT ... tgeompointseq(array_agg(tgeompointinst(.....))) FROM xxx_input"`
* the program exits (normally)

At this point it seems that I can use psql to view and select data as desired.

However, (again using psql at the command prompt), if I manually issue `"ALTER TABLE tz_yyyy_mm_dd SET (autovacuum_enabled = true, toast.autovacuum_enabled = true);"` postgresql crashes and restarts.

I'm using R for this.  Tomorrow I may try to convert over to Python; that may provide more control over the "cursor.execute()", "connection.commit()", and "connectionObject.close()".  Maybe R is not doing those properly.
 
Thank you for your time,
Wendell

**Comment by estebanzimanyi** [comment]
Dear Wendell

Would be possible for us to have access to the data so we can reproduce the
error ? That would be great.

Regards

Esteban

**Comment by wendellwt** [comment]
Esteban,

Ok, now I can recreate it from the command line (without R or Python).  Attached is the script and sample data.  Create a database and add the extensions, then run the script.  After a while (I suppose that is when autovacuum runs), postgresql crashes.

Wendell
[sample_crash.zip](https://github.com/ULB-CoDE-WIT/MobilityDB/files/4161132/sample_crash.zip)

**Comment by estebanzimanyi** [comment]
Dear Wendell
Many thanks for allowing us to discover a problem in the spatial statistics collection! I have fixed the problem in the master branch. Could you please verify whether everything is working OK for you?
Esteban

**Comment by wendellwt** [comment]
Yes, that works!  Thank you.

Wendell

**Comment by estebanzimanyi** [comment]
Great to know !

If you want to share with us some information about your application, we
are setting up a section in the Github page entitled "Users' applications".

I will start this section referencing the work of Nina Belyasvkaya with
Moscow public transportation that was presented this week in PgConf Russia.

Regards

Esteban

------------------------------------------------------------
Prof. Esteban Zimanyi
Department of Computer & Decision Engineering  (CoDE) CP 165/15
Universite Libre de Bruxelles
Avenue F. D. Roosevelt 50
B-1050 Brussels, Belgium
fax: + 32.2.650.47.13
tel: + 32.2.650.31.85
e-mail: ezimanyi@ulb.ac.be
Internet: http://cs.ulb.ac.be/members/esteban/
------------------------------------------------------------

**Comment by wendellwt** [comment]
Esteban,

Yes, I would like to help you as much as I can.  I would very much like to contribute to the "User applications" section.

However, although I think your MobilityDB is great, not everyone in my office agrees with me.  It may take me a while to create scenarios and solutions that show off the features of your database.
The office environment is very much Oracle-based.  So I need to do some work to convince them to use PostgreSQL, and PostGIS, and MobilityDB.  I'm working on it.

Wendell
