### ISSUE TITLE
Problem with operator

### ISSUE THREAD

**Issue by iryawisnubhadra** [ULB-CoDE-WIT/MobilityDB#5]
Dear Esteban

last month, i installed MobilityDB using docker in my Ubuntu platform
this database was working fine..

Until i have try to using the temporal operators like &=, #<, etc
This operator not working in my Ubuntu installation, but it did well when i used 
the demo version, in demo.mobilitydb.eu

Do you have some explanation ?

regards
Irya Wisnubhadra

**Comment by estebanzimanyi** [comment]
Dear Irya
Many thanks for your interest in MobilityDB. Could you please provide us more information about what is the problem ? Examples of data that cause the problem could help us to find out quicker the reason. Please notice that the version in demo.mobilitydb.eu is not up-to-date with the latest version of MobilityDB in github.
Regards
Esteban

**Comment by estebanzimanyi** [comment]
As another suggestion you could install the latest version of MobilityDB in the branch master at github. We have improved the code and corrected several issues.

**Comment by iryawisnubhadra** [comment]
Dear Esteban..

This is the sample..

I am using Ubuntu 18 Bionic Beaver.. with Docker Container


dell@dell-Inspiron-3480:~$ sudo docker exec -t -i mobility psql "host=localhost port=5432 dbname=mobilitydb user=docker password=docker" 
psql (11.6 (Debian 11.6-1.pgdg100+1))
SSL connection (protocol: TLSv1.3, cipher: TLS_AES_256_GCM_SHA384, bits: 256, compression: off)
Type "help" for help.

mobilitydb=# select tboolseq '[true@2001-01-01 08:00:00, true@2001-01-03 08:00:00]';
ERROR:  type "tboolseq" does not exist
LINE 1: select tboolseq '[true@2001-01-01 08:00:00, true@2001-01-03 ...

mobilitydb=# select tbooli '{true@2001-01-01 08:00:00, false@2001-01-03 08:00:00}';
ERROR:  type "tbooli" does not exist
LINE 1: select tbooli '{true@2001-01-01 08:00:00, false@2001-01-03 0...

regards
Irya W

**Comment by estebanzimanyi** [comment]
Dear Irya

Most probably you are using an old version of the API. Could you please
have a look at the manual available in github ?

Esteban

**Comment by iryawisnubhadra** [comment]
Thank you
