### ISSUE TITLE
what is trajectory()?

### ISSUE THREAD

**Issue by wendellwt** [ULB-CoDE-WIT/MobilityDB#8]
Esteban and others,

I see references in the manual and in the workbook to the "trajectory()" function.  How is it used?

I've created a field in postgis using "my_traj tgeogpoint" and populated it with "insert into ... tgeogpointseq(array_agg(tgeogpointinst(...)))" and that seems to work fine.  Using that, functions such as "tintersects(my_traj, a_poly)" seem to produce the appropriate results (and it is _really_ fast!).

Does "trajectory()" convert a tgeogpointseq structure into a PostGIS geometry so that functions such as ST_Distance can be used?  What is the difference in MobilityDB's nearestApproachDistance() and PostGIS's ST_Distance()?  Is a "trajectory()" item something that can be imported into QGIS or MovingPandas?

As I mentioned, everything seems to be working great.  Am I missing something by not using "trajectory()"?

Thank you,
Wendell

**Comment by estebanzimanyi** [comment]
Dear Wendell

Many thanks for letting us now your experiences with MobilityDB. In the future you may contact me by email at the address estebanzimanyi@gmail.com if this is more convenient for you.

The function has a signature trajectory(tgeompoint): geometry. It results in a spatial projection (that is, without time) of the temporal point to produce a PostGIS geometry. An example is given next.

SELECT ST_AsText(trajectory(tgeompoint '[Point(1 1)@2000-01-01,Point(2 2)@2000-01-02,Point(3 1)@2000-01-03]'))
"LINESTRING(1 1,2 2,3 1)"

Notice that the output of this function can be a geometry of type (Multi)Point or (Multi)Linestring.

As you rightfully describe you can use any PostGIS function on the result of such function. We typically add a column to a table containing the temporal points and fill it, e.g., as follows

UPDATE Trips SET Traj = trajectory(Trip);

to visualize the temporal points, e.g., in QGIS.

Regards

Esteban

**Comment by wendellwt** [comment]
Thank you for that response.  I figured it was something like that.

BTW, my usual print method for tgeompoint is:
 SELECT replace(asText(tgeompoint '[Point(1 1)@2000-01-01,Point(2 2)@2000-01-02,Point(3 1)@2000-01-03]'),',',E'\n') as tgeom;
                tgeom
-------------------------------------
 [POINT(1 1)@2000-01-01 00:00:00+00 +
  POINT(2 2)@2000-01-02 00:00:00+00 +
  POINT(3 1)@2000-01-03 00:00:00+00]

Thanks,
Wendell
