### ISSUE TITLE
function AtMin

### ISSUE THREAD

**Issue by iryawisnubhadra** [ULB-CoDE-WIT/MobilityDB#9]
Dear Esteban

MobilityDB is a good extension for MOs objects..
I have executed the following query

select d.id,twavg(speed(trip)) ,
startValue(atMax (speed(trip)*3.6)) 
from delivery d, truck t 
where d.truckid = t.truckid

and the server did it well...

but when I added the AtMin function

select atMin (speed(trip)*3.6) 
from delivery d, truck t 
where d.truckid = t.truckid

it becomes failed, SQL Error [57P03]: FATAL: the database system is in recovery mode
I am using DBeaver 6.3.4 Community edition

regards
Irya Wisnubhadra

**Comment by estebanzimanyi** [comment]
Dear Irya
Many thanks for reporting the problem. It is now fixed in the master branch in github.
Regards
Esteban
